name = "TurboMachineModel"
uuid = "e6d4ee7f-3a48-4fd3-b06b-ff730f84e90c"
version = "0.1.0"
authors = ["James"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.41.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
