name = "TurboMachineModel"
uuid = "e6d4ee7f-3a48-4fd3-b06b-ff730f84e90c"
authors = ["James"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
