name = "TurboMachineModel"
uuid = "e6d4ee7f-3a48-4fd3-b06b-ff730f84e90c"
version = "0.1.0"
authors = ["James"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
HDF5 = "0.17"
Plots = "1.41.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
